# Generated by Django 4.2.7 on 2024-01-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('User_ID', models.CharField(max_length=50)),
                ('Concern', models.CharField(max_length=50)),
                ('Help', models.CharField(max_length=60)),
                ('Feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
