# Generated by Django 4.2.7 on 2024-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AISFEEDBACKAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=50)),
                ('Full_Name', models.CharField(max_length=50)),
                ('User_ID', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('Address', models.CharField(max_length=60)),
                ('Password1', models.CharField(max_length=50)),
                ('Password2', models.CharField(max_length=50)),
            ],
        ),
    ]
