# Generated by Django 4.2.7 on 2024-01-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AISFEEDBACKAPP', '0002_registerpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpage',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=50),
        ),
    ]
