# Generated by Django 4.2.7 on 2024-01-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AISFEEDBACKAPP', '0003_alter_registerpage_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackpage',
            name='User_ID',
        ),
    ]
